# Generated by Django 4.1.1 on 2022-09-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0011_profile_fb_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fb_url',
            new_name='facebook_url',
        ),
    ]
